import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import "./globals.css";
import { ReduxProvider } from "react-redux";
import { ThemeProvider } from "next-themes";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "lo-fi.",
  description: "Generated by create next app",
};

 function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ThemeProvider>

          {children}

          </ThemeProvider>
          </AppRouterCacheProvider>
          
          </body>
    </html>
  );
}
export default RootLayout;